' ******************************************************************************
' swxJRNL.swj - journal recorded on 03/07/04 by silvestre
' ******************************************************************************

Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long
Dim Annotation As Object
Dim Gtol As Object
Dim DatumTag As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()
Set swApp = CreateObject ("SldWorks.Application")
Set Part = swApp.OpenDoc4 ("I:\Cordeuse\envoi2004\SW et M3D\système_tension\reduc_pignon.SLDASM", 2, 0, "", longstatus)
Set Part = swApp.ActivateDoc ("reduc_pignon.SLDASM")
Part.SelectByID "", "EDGE", 0.003329746948748, 0.02217533610411, 0.008603104687097
Part.ViewDisplayShaded
Part.ViewDisplayShaded
Part.ViewRotateplusx
Part.ViewRotateplusx
Part.ViewRotateplusx
Part.ClearSelection
Part.Save2 FALSE
Set Part = Nothing
swApp.CloseDoc "reduc_pignon.SLDASM"
swApp.ExitApp
End Sub
